import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import '../core/auth/auth_service.dart';
import '../core/onboarding/interests_store.dart';
import '../app/theme/nexus_theme.dart';
import '../shared/app_icons.dart';

/// Everlore splash — Phase 2 of the premium redesign.
///
/// Design language (sandboxed here before it propagates):
///   • Dark neumorphism — surfaces extrude from the void with a faint top-left
///     light bevel and a deep bottom-right shadow.
///   • Skeuomorphism   — the central sigil reads as polished forged metal:
///     gold gradient, beveled rim, a specular highlight that sweeps across it.
///   • Anime-3D motion — twelve character portraits orbit on two counter-
///     rotating elliptical rings (front discs larger/brighter for fake depth),
///     embers drift, and EVERLORE engraves in letter by letter.
///
/// Character discs load from `assets/splash/<key>.png` (generated by the backend
/// `gen:splash-avatars` script). Missing portraits fall back to neumorphic
/// gold-rimmed placeholder discs, so the splash always looks intentional.
///
/// Pure Flutter (CustomPaint + controllers). No new packages.
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

// Curated 12 voices, split across two rings. Keys match the backend script's
// output filenames (assets/splash/<key>.png).
const List<_OrbChar> _innerRing = [
  _OrbChar('tsundere', 'Ts'),
  _OrbChar('kdrama', 'Kd'),
  _OrbChar('cozy_comfort', 'Cz'),
  _OrbChar('shonen', 'Sh'),
  _OrbChar('litrpg', 'Lr'),
];
const List<_OrbChar> _outerRing = [
  _OrbChar('yandere', 'Yn'),
  _OrbChar('cyberpunk', 'Cy'),
  _OrbChar('dark_romance', 'Dr'),
  _OrbChar('dark_academia', 'Da'),
  _OrbChar('epic_fantasy', 'Ef'),
  _OrbChar('noir', 'No'),
  _OrbChar('horror', 'Hr'),
];

// Orbit geometry — shared by the disc layout and the 3D ring painter so the
// rings act as the visible "tracks" the character discs ride on.
const Offset _kOrbitCenter = Offset(180, 180);
const double _kOuterRx = 150;
const double _kOuterTilt = 0.50; // ry/rx — deep track, clear of inner beads
const double _kInnerRx = 82;
const double _kInnerTilt =
    0.30; // flatter inner track avoids cross-ring overlap

class _SplashScreenState extends State<SplashScreen>
    with TickerProviderStateMixin {
  late final AnimationController _intro; // one-shot entrance
  late final AnimationController _ambient; // embers + specular sweep
  late final AnimationController _orbit; // slow continuous revolution

  late final Animation<double> _sigilRise;
  late final Animation<double> _ringsReveal; // discs fly outward + fade
  late final Animation<double> _wordReveal; // EVERLORE letters
  late final Animation<double> _taglineFade;

  @override
  void initState() {
    super.initState();

    _intro = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 2600),
    );
    _ambient = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 3600),
    )..repeat();
    _orbit = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 26000),
    )..repeat();

    _sigilRise = CurvedAnimation(
      parent: _intro,
      curve: const Interval(0.0, 0.5, curve: Curves.easeOutCubic),
    );
    _ringsReveal = CurvedAnimation(
      parent: _intro,
      curve: const Interval(0.28, 0.72, curve: Curves.easeOutCubic),
    );
    _wordReveal = CurvedAnimation(
      parent: _intro,
      curve: const Interval(0.55, 0.92, curve: Curves.easeOut),
    );
    _taglineFade = CurvedAnimation(
      parent: _intro,
      curve: const Interval(0.82, 1.0, curve: Curves.easeIn),
    );

    _intro.forward().then((_) => _checkAuth());
  }

  Future<void> _checkAuth() async {
    // Hold on the fully-revealed orbit so it can breathe before navigating.
    await Future.delayed(const Duration(milliseconds: 1200));
    if (!mounted) return;
    final user = await AuthService.getCachedUser();
    if (!mounted) return;
    if (user != null) {
      // Same destination as post-auth: Discover, or interests onboarding if
      // this device hasn't finished it yet.
      final onboarded = await InterestsStore.isOnboarded();
      if (!mounted) return;
      context.go(onboarded ? '/discover' : '/onboarding');
    } else {
      context.go('/welcome');
    }
  }

  @override
  void dispose() {
    _intro.dispose();
    _ambient.dispose();
    _orbit.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: EverloreTheme.void0,
      body: AnimatedBuilder(
        animation: Listenable.merge([_intro, _ambient, _orbit]),
        builder: (context, _) {
          final amb = _ambient.value;
          return Stack(
            fit: StackFit.expand,
            children: [
              // 1 · Ambient void floor — radial vignette + drifting embers.
              CustomPaint(painter: _AmbientPainter(amb)),

              // 2 · The orbital theatre (rings + discs + central sigil).
              Center(
                child: SizedBox(
                  width: 360,
                  height: 360,
                  child: _OrbitTheatre(
                    orbit: _orbit.value,
                    sweep: amb,
                    sigilRise: _sigilRise.value,
                    ringsReveal: _ringsReveal.value,
                  ),
                ),
              ),

              // 3 · Wordmark + tagline, anchored below the theatre.
              Align(
                alignment: const Alignment(0, 0.62),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    _EngravedWordmark(reveal: _wordReveal.value),
                    const SizedBox(height: 14),
                    Opacity(
                      opacity: _taglineFade.value,
                      child: Text(
                        'A LIVING WORLD AWAITS',
                        style: TextStyle(
                          fontFamily: EverloreTheme.uiFamily,
                          color: EverloreTheme.ash,
                          fontSize: 11,
                          fontWeight: FontWeight.w600,
                          letterSpacing: 4.0,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}

/// Lays out the two counter-rotating rings of character discs around the
/// central forged sigil, with painter'd energy rings behind them.
class _OrbitTheatre extends StatelessWidget {
  final double orbit; // 0..1 continuous
  final double sweep; // 0..1 ambient
  final double sigilRise; // 0..1
  final double ringsReveal; // 0..1
  const _OrbitTheatre({
    required this.orbit,
    required this.sweep,
    required this.sigilRise,
    required this.ringsReveal,
  });

  @override
  Widget build(BuildContext context) {
    final discs = <_PlacedDisc>[];

    // Outer ring — clockwise.
    _layoutRing(
      ring: _outerRing,
      center: _kOrbitCenter,
      rx: _kOuterRx,
      ry: _kOuterRx * _kOuterTilt,
      baseAngle: orbit * 2 * math.pi,
      baseSize: 50,
      reveal: ringsReveal,
      out: discs,
    );
    // Inner ring — counter-clockwise, phase-shifted.
    _layoutRing(
      ring: _innerRing,
      center: _kOrbitCenter,
      rx: _kInnerRx,
      ry: _kInnerRx * _kInnerTilt,
      baseAngle: -orbit * 2 * math.pi * 1.35 + 0.6,
      baseSize: 48,
      reveal: ringsReveal,
      out: discs,
    );

    // Painter's algorithm: back (small depth) first, front last.
    discs.sort((a, b) => a.depth.compareTo(b.depth));

    return Stack(
      clipBehavior: Clip.none,
      children: [
        // FAR half of the orbit rings — passes behind the sigil.
        Positioned.fill(
          child: CustomPaint(
            painter: _OrbitRingsPainter(
              glint: sweep,
              reveal: ringsReveal,
              front: false,
            ),
          ),
        ),
        // Discs that sit BEHIND the sigil (depth < 0).
        ...discs.where((d) => d.depth < 0).map((d) => d.toWidget()),
        // Central forged sigil.
        Center(
          child: Transform.translate(
            offset: Offset(0, (1 - sigilRise) * 22),
            child: Transform.scale(
              scale: 0.86 + sigilRise * 0.14,
              child: Opacity(
                opacity: sigilRise.clamp(0.0, 1.0),
                child: _ForgedSigil(sweep: sweep),
              ),
            ),
          ),
        ),
        // NEAR half of the orbit rings — crosses in front of the sigil.
        Positioned.fill(
          child: CustomPaint(
            painter: _OrbitRingsPainter(
              glint: sweep,
              reveal: ringsReveal,
              front: true,
            ),
          ),
        ),
        // Discs IN FRONT of the sigil (depth >= 0) — beads on the near rim.
        ...discs.where((d) => d.depth >= 0).map((d) => d.toWidget()),
      ],
    );
  }

  void _layoutRing({
    required List<_OrbChar> ring,
    required Offset center,
    required double rx,
    required double ry,
    required double baseAngle,
    required double baseSize,
    required double reveal,
    required List<_PlacedDisc> out,
  }) {
    final r = Curves.easeOutCubic.transform(reveal.clamp(0.0, 1.0));
    for (var i = 0; i < ring.length; i++) {
      final angle = baseAngle + i / ring.length * 2 * math.pi;
      final depth = math.sin(angle); // -1 back .. +1 front
      // discs fly outward from center as they reveal
      final ex = math.cos(angle) * rx * r;
      final ey = depth * ry * r;
      final scale = (0.62 + (depth + 1) / 2 * 0.46); // back small, front big
      final opacity = (0.42 + (depth + 1) / 2 * 0.58) * r;
      out.add(
        _PlacedDisc(
          ch: ring[i],
          pos: center + Offset(ex, ey),
          size: baseSize * scale,
          opacity: opacity.clamp(0.0, 1.0),
          depth: depth,
        ),
      );
    }
  }
}

class _OrbChar {
  final String key;
  final String initials; // fallback label when portrait is missing
  const _OrbChar(this.key, this.initials);
}

class _PlacedDisc {
  final _OrbChar ch;
  final Offset pos;
  final double size;
  final double opacity;
  final double depth;
  const _PlacedDisc({
    required this.ch,
    required this.pos,
    required this.size,
    required this.opacity,
    required this.depth,
  });

  Widget toWidget() {
    return Positioned(
      left: pos.dx - size / 2,
      top: pos.dy - size / 2,
      width: size,
      height: size,
      child: Opacity(
        opacity: opacity,
        child: _AvatarDisc(ch: ch, size: size),
      ),
    );
  }
}

/// A circular character portrait with a neumorphic raised gold rim. Falls back
/// to a gold-on-void placeholder disc with the voice initials if the asset is
/// absent (i.e. before the generation script has been run).
class _AvatarDisc extends StatelessWidget {
  final _OrbChar ch;
  final double size;
  const _AvatarDisc({required this.ch, required this.size});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        border: Border.all(
          color: EverloreTheme.goldDim.withValues(alpha: 0.7),
          width: 1.4,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.55),
            blurRadius: 10,
            offset: const Offset(3, 4),
          ),
          BoxShadow(
            color: EverloreTheme.gold.withValues(alpha: 0.10),
            blurRadius: 14,
            spreadRadius: 1,
          ),
        ],
      ),
      child: ClipOval(child: _portrait()),
    );
  }

  /// Loads the WebP portrait the generation script produces (~10KB, 320px),
  /// falling back to a neumorphic placeholder if it hasn't been generated yet.
  Widget _portrait() {
    return Image.asset(
      'assets/splash/${ch.key}.webp',
      fit: BoxFit.cover,
      gaplessPlayback: true,
      errorBuilder: (context, _, __) => _placeholder(),
    );
  }

  Widget _placeholder() {
    return Container(
      decoration: const BoxDecoration(
        shape: BoxShape.circle,
        gradient: RadialGradient(
          center: Alignment(-0.3, -0.4),
          colors: [EverloreTheme.void3, EverloreTheme.void0],
        ),
      ),
      alignment: Alignment.center,
      child: Text(
        ch.initials,
        style: GoogleFonts.cinzel(
          color: EverloreTheme.gold.withValues(alpha: 0.85),
          fontSize: size * 0.34,
          fontWeight: FontWeight.w700,
          letterSpacing: 0.5,
        ),
      ),
    );
  }
}

/// The centerpiece: a neumorphic disc with a skeuomorphic gold sigil engraved
/// into it and a specular highlight that sweeps across the metal.
class _ForgedSigil extends StatelessWidget {
  final double sweep; // 0..1 ambient phase
  const _ForgedSigil({required this.sweep});

  static const double _size = 116;

  @override
  Widget build(BuildContext context) {
    const lightEdge = Color(0x1AAFA8FF); // dark-neumorphic top-left bevel
    return Container(
      width: _size,
      height: _size,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: const RadialGradient(
          center: Alignment(-0.3, -0.4),
          radius: 1.1,
          colors: [EverloreTheme.void3, EverloreTheme.void0],
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.6),
            blurRadius: 26,
            offset: const Offset(10, 12),
          ),
          const BoxShadow(
            color: lightEdge,
            blurRadius: 20,
            offset: Offset(-9, -11),
          ),
          BoxShadow(
            color: EverloreTheme.gold.withValues(alpha: 0.12),
            blurRadius: 44,
            spreadRadius: 3,
          ),
        ],
      ),
      child: Stack(
        alignment: Alignment.center,
        children: [
          EvIcon(AppIcons.forgeSigil, size: _size * 0.72),
          IgnorePointer(
            child: Opacity(
              opacity: 0.22,
              child: Transform.translate(
                offset: Offset((sweep * 2 - 1) * _size * 0.5, 0),
                child: Container(
                  width: _size * 0.14,
                  height: _size * 0.82,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [
                        Colors.transparent,
                        EverloreTheme.goldGlow.withValues(alpha: 0.55),
                        Colors.transparent,
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// The two orbital-plane rings the discs ride on, rendered as 3D forged-metal
/// bands. Each ring is a tilted ellipse drawn as one half at a time (so the FAR
/// half can sit behind the sigil and the NEAR half in front). The band has a
/// neumorphic bevel — a light top-left highlight edge and a dark bottom-right
/// shadow edge — plus a skeuomorphic specular glint that travels around the rim.
class _OrbitRingsPainter extends CustomPainter {
  final double glint; // 0..1 traveling-light phase
  final double reveal; // 0..1 fade + grow-in
  final bool front; // near (bottom) half vs far (top) half
  _OrbitRingsPainter({
    required this.glint,
    required this.reveal,
    required this.front,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (reveal <= 0.01) return;
    final c = size.center(Offset.zero);
    final r = Curves.easeOutCubic.transform(reveal.clamp(0.0, 1.0));
    _ring(canvas, c, _kOuterRx * r, _kOuterRx * _kOuterTilt * r, glint, r);
    // Inner ring's glint is phase-offset so the two shines don't move in lockstep.
    _ring(
      canvas,
      c,
      _kInnerRx * r,
      _kInnerRx * _kInnerTilt * r,
      (glint + 0.5) % 1.0,
      r,
    );
  }

  void _ring(
    Canvas canvas,
    Offset c,
    double rx,
    double ry,
    double glintPhase,
    double a,
  ) {
    if (rx < 1) return;
    final start = front ? 0.0 : math.pi; // bottom half (sin>0) vs top half
    const sweep = math.pi;
    final rect = Rect.fromCenter(center: c, width: rx * 2, height: ry * 2);

    // Soft energy halo (neumorphic softness + anime glow).
    canvas.drawArc(
      rect,
      start,
      sweep,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 9
        ..color = EverloreTheme.gold.withValues(alpha: 0.05 * a)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 6),
    );

    // Forged-metal band base.
    canvas.drawArc(
      rect,
      start,
      sweep,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2.6
        ..strokeCap = StrokeCap.round
        ..color = EverloreTheme.goldDim.withValues(alpha: 0.6 * a),
    );

    // Neumorphic top-left highlight bevel.
    canvas.save();
    canvas.translate(-0.8, -1.2);
    canvas.drawArc(
      rect,
      start,
      sweep,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1.1
        ..color = EverloreTheme.goldGlow.withValues(alpha: 0.5 * a),
    );
    canvas.restore();

    // Neumorphic bottom-right shadow bevel.
    canvas.save();
    canvas.translate(0.8, 1.4);
    canvas.drawArc(
      rect,
      start,
      sweep,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1.3
        ..color = Colors.black.withValues(alpha: 0.5 * a),
    );
    canvas.restore();

    // Skeuomorphic specular glint travelling around the rim — drawn only while
    // its centre is on the half this pass renders, so it slides behind/in front
    // of the sigil naturally as it orbits.
    final ga = glintPhase * 2 * math.pi;
    final s = math.sin(ga);
    final onThisHalf = front ? s >= 0 : s < 0;
    if (onThisHalf) {
      const half = 0.45; // arc half-width (radians)
      // fade near the half boundary so it doesn't pop when crossing the sigil
      final edgeFade = (s.abs() / 0.35).clamp(0.0, 1.0);
      canvas.drawArc(
        rect,
        ga - half,
        half * 2,
        false,
        Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = 3.0
          ..strokeCap = StrokeCap.round
          ..color = EverloreTheme.goldGlow.withValues(alpha: 0.9 * a * edgeFade)
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 2.5),
      );
    }
  }

  @override
  bool shouldRepaint(_OrbitRingsPainter old) =>
      old.glint != glint || old.reveal != reveal || old.front != front;
}

/// Background vignette + a field of slow-drifting ember motes.
class _AmbientPainter extends CustomPainter {
  final double t;
  _AmbientPainter(this.t);

  static final List<_Ember> _embers = List.generate(18, (i) {
    final rnd = math.Random(i * 7 + 3);
    return _Ember(
      x: rnd.nextDouble(),
      baseY: rnd.nextDouble(),
      speed: 0.3 + rnd.nextDouble() * 0.7,
      size: 0.8 + rnd.nextDouble() * 1.8,
      phase: rnd.nextDouble(),
      gold: rnd.nextBool(),
    );
  });

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
      Offset.zero & size,
      Paint()
        ..shader = RadialGradient(
          center: const Alignment(0, -0.12),
          radius: 0.9,
          colors: [
            EverloreTheme.void2.withValues(alpha: 0.55),
            EverloreTheme.void0,
          ],
        ).createShader(Offset.zero & size),
    );

    for (final e in _embers) {
      final prog = (t * e.speed + e.phase) % 1.0;
      final y = (e.baseY - prog) % 1.0;
      final twinkle =
          0.3 + 0.7 * (0.5 + 0.5 * math.sin((prog + e.phase) * math.pi * 4));
      final dx =
          e.x * size.width + math.sin((prog + e.phase) * math.pi * 2) * 10;
      final dy = y * size.height;
      final color = e.gold
          ? EverloreTheme.goldGlow
          : EverloreTheme.violetBright;
      canvas.drawCircle(
        Offset(dx, dy),
        e.size,
        Paint()
          ..color = color.withValues(alpha: 0.10 + twinkle * 0.22)
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 1.5),
      );
    }
  }

  @override
  bool shouldRepaint(_AmbientPainter old) => old.t != t;
}

class _Ember {
  final double x, baseY, speed, size, phase;
  final bool gold;
  const _Ember({
    required this.x,
    required this.baseY,
    required this.speed,
    required this.size,
    required this.phase,
    required this.gold,
  });
}

/// "EVERLORE" engraving in letter by letter, each with a letterpress depth
/// (dark drop behind a gold-gradient face).
class _EngravedWordmark extends StatelessWidget {
  final double reveal; // 0..1
  const _EngravedWordmark({required this.reveal});

  static const _letters = ['E', 'V', 'E', 'R', 'L', 'O', 'R', 'E'];

  @override
  Widget build(BuildContext context) {
    final base = GoogleFonts.cinzel(
      fontSize: 34,
      fontWeight: FontWeight.w700,
      letterSpacing: 8.0,
    );
    return ShaderMask(
      shaderCallback: (rect) => const LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [
          EverloreTheme.goldGlow,
          EverloreTheme.gold,
          EverloreTheme.goldDim,
        ],
        stops: [0.0, 0.5, 1.0],
      ).createShader(rect),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: List.generate(_letters.length, (i) {
          // Each letter reveals across its own slice of the timeline.
          final start = i / _letters.length * 0.7;
          final p = ((reveal - start) / 0.3).clamp(0.0, 1.0);
          final eased = Curves.easeOut.transform(p);
          return Opacity(
            opacity: eased,
            child: Transform.translate(
              offset: Offset(0, (1 - eased) * 6),
              child: Stack(
                children: [
                  Transform.translate(
                    offset: const Offset(0, 1.6),
                    child: Text(
                      _letters[i],
                      style: base.copyWith(
                        color: Colors.black.withValues(alpha: 0.6),
                      ),
                    ),
                  ),
                  Text(_letters[i], style: base.copyWith(color: Colors.white)),
                ],
              ),
            ),
          );
        }),
      ),
    );
  }
}
